project_id = "ofqaxojjqryylcugegke"

[functions.parse-cv-exhibitions]
verify_jwt = false

[functions.veriff-session]
verify_jwt = false

[functions.veriff-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-donation-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.donor-portal]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
